export const MAX_CACHED_PAGE_LIMIT_FOR_FEED = 5;
export const MAX_CACHED_USER_PHOTOS_PAGE_LIMIT = 5;
export const MAX_CACHED_USER_LIMIT = 5;
export const EXPIRE_DURATION = 3600 * 1000;
export const USER_TIMESTAMP_DATA_IDENTIFIER = 'USER-TIMESTAMP-DATA';
export enum CACHE_TYPES{
     USER_PHOTOS = "USER-PHOTOS",
     NEWS_FEED_PHOTOS = "NEWS-FEED-PHOTOS",
     USER_PROFILE = "USER-PROFILE"
};